import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import { getServerSession } from 'next-auth'

import Providers from '@/components/SessionProvider'
import { authConfig } from './api/auth/[...nextauth]/config'

const inter = Inter({
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = await getServerSession(authConfig)

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers session={session}>
                    <div className="flex flex-col justify-between h-full">
                        <Header />
                        <div className="h-full">{children}</div>
                        <Footer />
                    </div>
                </Providers>
            </body>
        </html>
    )
}
